name: Test Trivy

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t test-image .

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: test-image
          format: table
